name: DESDEO-emo 

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: ${{ runner.os }}-pip

  test:
    strategy:
      fail-fast: true
      matrix:
        os: [ "ubuntu-latest", "windows-latest", "macos-latest" ]
        python-version: [ "3.9", "3.10" ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      # Explicitly set PATH for Poetry on Windows
      - name: Set PATH for Poetry (Windows)
        if: runner.os == 'Windows'
        run: echo ".venv\Scripts" >> $GITHUB_PATH

      # Activate virtual environment and install dependencies for Windows
      - name: Activate virtual environment and install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          .venv\Scripts\Activate
          poetry install --no-interaction --no-root

      # Activate virtual environment and install dependencies for Linux/macOS
      - name: Activate virtual environment and install dependencies (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          source $GITHUB_WORKSPACE/.venv/bin/activate
          poetry install --no-interaction --no-root

      - name: Install library
        run: poetry install --no-interaction

      # Run tests for Windows
      - name: Run tests (Windows)
        if: runner.os == 'Windows'
        run: |
          .venv\Scripts\Activate
          pip install pytest-rerunfailures
          pytest tests/ --reruns 10

      # Run tests for Linux/macOS
      - name: Run tests (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          source .venv/bin/activate
          pip install pytest-rerunfailures
          pytest tests/ --reruns 10
